<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <OutputType>Exe</OutputType>
        <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
        <UseAppHost>true</UseAppHost>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../../src/braid/Braid.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="TUnit"/>
    </ItemGroup>
</Project>
